web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ../laravel:/code
    - ./docker/conf/:/etc/nginx/conf.d/
    - ./docker/www_logs/nginx:/var/log/nginx
  links:
    - phpfpm
phpfpm:
  build: docker/dockerContainers/php72-fpm
  command: bash -c "/etc/init.d/cron start && php-fpm -F"
  links:
    - db
  volumes:
    - ../laravel:/code
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./docker/dockerContainers/php72-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
  ports:
    - "9000:9000"
db:
  image: mysql:5.7
  restart: always
  volumes:
    - ./docker/mysql-data:/var/lib/mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: laravel
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=db
  links:
    - db
  restart: always
  ports:
    - 8081:80        